project:
  type: website
  output-dir: _site
website:
  title: "SaadAI Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: intro.qmd
        text: النظريات والأساسيات
      - href: math.qmd
        text: Mathematics
      - href: programming.qmd
        text: Programming
format:
  html:
    include-after-body: script.js
    lang: ar
    dir: rtl
    theme: cosmo
    css: styles.css